// Package generator converts JS AST nodes into JavaScript source code.
package generator

import (
	"fmt"
	"strings"

	"github.com/kmmz532/php2js/internal/jsast"
)

// Generator produces JavaScript source code from a JS AST.
type Generator struct {
	indent int
	buf    strings.Builder
}

// New creates a new Generator.
func New() *Generator {
	return &Generator{}
}

// Generate produces JavaScript source from a Program.
func (g *Generator) Generate(prog *jsast.Program) string {
	g.indent = 0
	g.buf.Reset()

	g.writef("// Auto-generated by php2js from %s\n", prog.SourceFile)
	g.writef("// Do not edit manually.\n\n")

	// Imports
	for _, imp := range prog.Imports {
		g.genImport(imp)
	}
	if len(prog.Imports) > 0 {
		g.writef("\n")
	}

	// Body
	for _, stmt := range prog.Body {
		g.genStmt(stmt)
	}

	return g.buf.String()
}

func (g *Generator) genImport(imp *jsast.ImportDecl) {
	if imp.Star != "" {
		g.writef("import * as %s from '%s';\n", imp.Star, imp.Path)
	} else if imp.Default != "" {
		if len(imp.Names) > 0 {
			g.writef("import %s, { %s } from '%s';\n", imp.Default, strings.Join(imp.Names, ", "), imp.Path)
		} else {
			g.writef("import %s from '%s';\n", imp.Default, imp.Path)
		}
	} else if len(imp.Names) > 0 {
		g.writef("import { %s } from '%s';\n", strings.Join(imp.Names, ", "), imp.Path)
	} else {
		g.writef("import '%s';\n", imp.Path)
	}
}

func (g *Generator) genStmt(stmt jsast.Statement) {
	if stmt == nil {
		return
	}
	switch s := stmt.(type) {
	case *jsast.ExprStatement:
		g.writeIndent()
		g.genExpr(s.Expr)
		g.writef(";\n")
	case *jsast.VarDecl:
		g.writeIndent()
		g.writef("%s %s", s.Kind, s.Name)
		if s.Init != nil {
			g.writef(" = ")
			g.genExpr(s.Init)
		}
		g.writef(";\n")
	case *jsast.FunctionDecl:
		g.genFunction(s)
	case *jsast.ClassDecl:
		g.genClass(s)
	case *jsast.IfStatement:
		g.genIf(s)
	case *jsast.ForStatement:
		g.genFor(s)
	case *jsast.ForOfStatement:
		g.genForOf(s)
	case *jsast.WhileStatement:
		g.genWhile(s)
	case *jsast.DoWhileStatement:
		g.genDoWhile(s)
	case *jsast.ReturnStatement:
		g.writeIndent()
		g.writef("return")
		if s.Value != nil {
			g.writef(" ")
			g.genExpr(s.Value)
		}
		g.writef(";\n")
	case *jsast.ThrowStatement:
		g.writeIndent()
		g.writef("throw ")
		g.genExpr(s.Value)
		g.writef(";\n")
	case *jsast.TryCatchStatement:
		g.genTryCatch(s)
	case *jsast.SwitchStatement:
		g.genSwitch(s)
	case *jsast.BreakStatement:
		g.writeIndent()
		g.writef("break;\n")
	case *jsast.ContinueStatement:
		g.writeIndent()
		g.writef("continue;\n")
	case *jsast.RawJS:
		g.writeIndent()
		g.writef("%s\n", s.Code)
	}
}

func (g *Generator) genFunction(fn *jsast.FunctionDecl) {
	g.writef("\n")
	g.writeIndent()
	if fn.IsExported {
		g.writef("export ")
	}
	if fn.IsAsync {
		g.writef("async ")
	}
	g.writef("function %s(", fn.Name)
	g.genParams(fn.Params)
	g.writef(") {\n")
	g.indent++
	for _, s := range fn.Body {
		g.genStmt(s)
	}
	g.indent--
	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genClass(cls *jsast.ClassDecl) {
	g.writef("\n")
	g.writeIndent()
	if cls.IsExported {
		g.writef("export ")
	}
	g.writef("class %s", cls.Name)
	if cls.Extends != "" {
		g.writef(" extends %s", cls.Extends)
	}
	g.writef(" {\n")
	g.indent++

	for _, prop := range cls.Properties {
		g.writeIndent()
		if prop.IsStatic {
			g.writef("static ")
		}
		g.writef("%s", prop.Name)
		if prop.Init != nil {
			g.writef(" = ")
			g.genExpr(prop.Init)
		}
		g.writef(";\n")
	}

	for _, method := range cls.Methods {
		g.writef("\n")
		g.writeIndent()
		if method.IsStatic {
			g.writef("static ")
		}
		if method.IsAsync {
			g.writef("async ")
		}
		g.writef("%s(", method.Name)
		g.genParams(method.Params)
		g.writef(") {\n")
		g.indent++
		for _, s := range method.Body {
			g.genStmt(s)
		}
		g.indent--
		g.writeIndent()
		g.writef("}\n")
	}

	g.indent--
	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genIf(s *jsast.IfStatement) {
	g.writeIndent()
	g.writef("if (")
	g.genExpr(s.Condition)
	g.writef(") {\n")
	g.indent++
	for _, st := range s.Body {
		g.genStmt(st)
	}
	g.indent--

	for _, ei := range s.ElseIf {
		g.writeIndent()
		g.writef("} else if (")
		g.genExpr(ei.Condition)
		g.writef(") {\n")
		g.indent++
		for _, st := range ei.Body {
			g.genStmt(st)
		}
		g.indent--
	}

	if len(s.Else) > 0 {
		g.writeIndent()
		g.writef("} else {\n")
		g.indent++
		for _, st := range s.Else {
			g.genStmt(st)
		}
		g.indent--
	}

	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genFor(s *jsast.ForStatement) {
	g.writeIndent()
	g.writef("for (")
	if s.Init != nil {
		if es, ok := s.Init.(*jsast.ExprStatement); ok {
			g.genExpr(es.Expr)
		}
	}
	g.writef("; ")
	if s.Condition != nil {
		g.genExpr(s.Condition)
	}
	g.writef("; ")
	if s.Update != nil {
		g.genExpr(s.Update)
	}
	g.writef(") {\n")
	g.indent++
	for _, st := range s.Body {
		g.genStmt(st)
	}
	g.indent--
	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genForOf(s *jsast.ForOfStatement) {
	g.writeIndent()
	if s.Key != "" {
		g.writef("for (let [%s, %s] of __runtime.entries(", s.Key, s.Value)
		g.genExpr(s.Iter)
		g.writef(")) {\n")
	} else {
		g.writef("for (let %s of __runtime.values(", s.Value)
		g.genExpr(s.Iter)
		g.writef(")) {\n")
	}
	g.indent++
	for _, st := range s.Body {
		g.genStmt(st)
	}
	g.indent--
	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genWhile(s *jsast.WhileStatement) {
	g.writeIndent()
	g.writef("while (")
	g.genExpr(s.Condition)
	g.writef(") {\n")
	g.indent++
	for _, st := range s.Body {
		g.genStmt(st)
	}
	g.indent--
	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genDoWhile(s *jsast.DoWhileStatement) {
	g.writeIndent()
	g.writef("do {\n")
	g.indent++
	for _, st := range s.Body {
		g.genStmt(st)
	}
	g.indent--
	g.writeIndent()
	g.writef("} while (")
	g.genExpr(s.Condition)
	g.writef(");\n")
}

func (g *Generator) genTryCatch(s *jsast.TryCatchStatement) {
	g.writeIndent()
	g.writef("try {\n")
	g.indent++
	for _, st := range s.Try {
		g.genStmt(st)
	}
	g.indent--

	for _, c := range s.Catches {
		g.writeIndent()
		g.writef("} catch (%s) {\n", c.Param)
		g.indent++
		for _, st := range c.Body {
			g.genStmt(st)
		}
		g.indent--
	}

	if len(s.Finally) > 0 {
		g.writeIndent()
		g.writef("} finally {\n")
		g.indent++
		for _, st := range s.Finally {
			g.genStmt(st)
		}
		g.indent--
	}

	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genSwitch(s *jsast.SwitchStatement) {
	g.writeIndent()
	g.writef("switch (")
	g.genExpr(s.Discriminant)
	g.writef(") {\n")
	g.indent++
	for _, c := range s.Cases {
		g.writeIndent()
		if c.Test == nil {
			g.writef("default:\n")
		} else {
			g.writef("case ")
			g.genExpr(c.Test)
			g.writef(":\n")
		}
		g.indent++
		for _, st := range c.Body {
			g.genStmt(st)
		}
		g.indent--
	}
	g.indent--
	g.writeIndent()
	g.writef("}\n")
}

func (g *Generator) genParams(params []*jsast.Param) {
	for i, p := range params {
		if i > 0 {
			g.writef(", ")
		}
		if p.Rest {
			g.writef("...")
		}
		g.writef("%s", p.Name)
		if p.Default != nil {
			g.writef(" = ")
			g.genExpr(p.Default)
		}
	}
}

func (g *Generator) genExpr(expr jsast.Expression) {
	if expr == nil {
		g.writef("undefined")
		return
	}
	switch e := expr.(type) {
	case *jsast.Identifier:
		g.writef("%s", e.Name)
	case *jsast.Literal:
		g.writef("%s", e.Value)
	case *jsast.TemplateLiteral:
		g.writef("`")
		for _, part := range e.Parts {
			if lit, ok := part.(*jsast.Literal); ok && lit.Kind == "string" {
				// Raw string part - strip quotes
				s := lit.Value
				s = strings.TrimPrefix(s, `"`)
				s = strings.TrimSuffix(s, `"`)
				g.writef("%s", s)
			} else {
				g.writef("${")
				g.genExpr(part)
				g.writef("}")
			}
		}
		g.writef("`")
	case *jsast.BinaryExpr:
		g.writef("(")
		g.genExpr(e.Left)
		g.writef(" %s ", e.Op)
		g.genExpr(e.Right)
		g.writef(")")
	case *jsast.UnaryExpr:
		if e.Prefix {
			g.writef("%s ", e.Op)
			g.genExpr(e.Operand)
		} else {
			g.genExpr(e.Operand)
			g.writef(" %s", e.Op)
		}
	case *jsast.UpdateExpr:
		if e.Prefix {
			g.writef("%s", e.Op)
			g.genExpr(e.Operand)
		} else {
			g.genExpr(e.Operand)
			g.writef("%s", e.Op)
		}
	case *jsast.AssignExpr:
		g.genExpr(e.Left)
		g.writef(" %s ", e.Op)
		g.genExpr(e.Right)
	case *jsast.CallExpr:
		if e.Await {
			g.writef("await ")
		}
		g.genExpr(e.Callee)
		g.writef("(")
		for i, arg := range e.Args {
			if i > 0 {
				g.writef(", ")
			}
			g.genExpr(arg)
		}
		g.writef(")")
	case *jsast.NewExpr:
		g.writef("new ")
		g.genExpr(e.Callee)
		g.writef("(")
		for i, arg := range e.Args {
			if i > 0 {
				g.writef(", ")
			}
			g.genExpr(arg)
		}
		g.writef(")")
	case *jsast.MemberExpr:
		g.genExpr(e.Object)
		if e.Computed {
			g.writef("[")
			g.genExpr(e.Property)
			g.writef("]")
		} else {
			g.writef(".")
			g.genExpr(e.Property)
		}
	case *jsast.ArrayExpr:
		g.writef("[")
		for i, el := range e.Elements {
			if i > 0 {
				g.writef(", ")
			}
			if el != nil {
				g.genExpr(el)
			}
		}
		g.writef("]")
	case *jsast.ObjectExpr:
		g.writef("{ ")
		for i, prop := range e.Properties {
			if i > 0 {
				g.writef(", ")
			}
			if prop.Computed {
				g.writef("[")
				g.genExpr(prop.Key)
				g.writef("]: ")
			} else if prop.Key != nil {
				g.genExpr(prop.Key)
				g.writef(": ")
			}
			g.genExpr(prop.Value)
		}
		g.writef(" }")
	case *jsast.ConditionalExpr:
		g.writef("(")
		g.genExpr(e.Test)
		g.writef(" ? ")
		g.genExpr(e.Consequent)
		g.writef(" : ")
		g.genExpr(e.Alternate)
		g.writef(")")
	case *jsast.LogicalExpr:
		g.writef("(")
		g.genExpr(e.Left)
		g.writef(" %s ", e.Op)
		g.genExpr(e.Right)
		g.writef(")")
	case *jsast.ArrowFunc:
		if e.IsAsync {
			g.writef("async ")
		}
		g.writef("(")
		g.genParams(e.Params)
		g.writef(") => {\n")
		g.indent++
		for _, st := range e.Body {
			g.genStmt(st)
		}
		g.indent--
		g.writeIndent()
		g.writef("}")
	case *jsast.SpreadExpr:
		g.writef("...")
		g.genExpr(e.Argument)
	case *jsast.AwaitExpr:
		g.writef("await ")
		g.genExpr(e.Argument)
	case *jsast.NullCoalesceExpr:
		g.writef("(")
		g.genExpr(e.Left)
		g.writef(" ?? ")
		g.genExpr(e.Right)
		g.writef(")")
	}
}

func (g *Generator) writef(format string, args ...any) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) writeIndent() {
	for i := 0; i < g.indent; i++ {
		g.buf.WriteString("  ")
	}
}
